<template lang="html">
  <div class="notify" id="notifyDiv"> <strong id="#msg">{{msg}}</strong></div>
  <div class="container">

  <label for="search"><strong>Search By id</strong></label>
  <input type="number" v-model="searchId" name="search" >
  <input type="button"   v-on:click="getPayment" value="search"  >
<br>
  <label for="datecreated"><strong>date</strong></label>
  <input type="date" name='datecreated' v-model="payment.dateCreated" >
  <label for='pMethod'><strong>Method</strong></label>
    <select name="pMethod" v-model="payment.method">
      <option>WIRE</option>
      <option>VISA</option>
    </select>
    <br>
    <label for="pvalue"><strong>Value</strong></label>
    <input type="number"  name="pvalue" v-model="payment.value" step=".01">
    <label for="search"><strong>Invoice id</strong></label>
    <input type="number" v-model="payment.invoice_id" >
    <div class="inputDiv">
      <input type="button" @click="edit" name="edit" value="Edit" >
      <input type="button" @click="create" name="create" value="create">
    </div>
  </div>
  <!-- <button type="button" @click='navigateToHome'>go to Home</button>
  <p>id : {{id}}</p>
  <p>hi</p>
  <label for="getPayment">getPayment By id</label>
  <input type="text" name="getPayment"  v-model.lazy="message">
  <p>Message is: {{ message }}</p>


   <button type="button" name="button"  v-on:click="getPayment"> search</button>
  <p>{{ payment }}</p> -->

  <!-- <form action="http://localhost:8080/payments/add" method="post" >
  <label for="fname">method</label>
  <input type="text"  name="method"><br><br>
  <label for="lname">value</label>
  <input type="text"  name="value"><br><br>
  <input type="submit" value="Submit">
</form> -->

</template>

<script>
export default {

  data(){
    return{
      // id:this.$route.params.id
      searchId:"",
      payment:{},
      pMethod:"",
      pValue:"",
      pInvoiceId:"",
      msg:""
    }
  },
  methods:{
    alertMessage(message,state='normal'){
        this.msg=message;
        let notifyDiv = document.getElementById('notifyDiv');
        if(state=="success"){
          notifyDiv.classList.add("success");
        }else if (state=="failure") {
          notifyDiv.classList.add("failure");
        }
        notifyDiv.classList.add("active");

        setTimeout(function(){
           notifyDiv.classList.remove("active","failure","success");
        },2500)
      },
  async  getPayment(){
    if(!this.searchId){
      this.alertMessage("enter an ID Please");
      return;
    }
    try{  const { data } = await this.axios.get(
           "http://localhost:8080/payments/"+this.searchId
         );

         this.payment=data.payment
         console.log(data);
         this.payment.dateCreated=new Date(this.payment.dateCreated);
         this.payment.dateCreated=this.payment.dateCreated.toISOString().split("T")[0];
         this.payment.invoice_id=data.id_invoice
        }catch(e){
           console.log("not found");
           this.alertMessage("Id not found");
        }},

    async edit(){
      if(!this.searchId){this.alertMessage("please Search first to Edit ") ;return;}
          if(!this.payment){this.alertMessage("Search First For a Payment");return ;}

        if(!this.getinvoice(this.payment.invoice_id)){this.alertMessage("invoice Id Not Found !!") ; throw 400;
      }
      else{
          try{
                await this.axios.post(
                 "http://localhost:8080/payments/edit", {...this.payment}

               );
               this.alertMessage("Edited successfully ","success");
               this.payment={};
              }catch(e){
                 this.alertMessage("Not Found!")
              }}
     },
      async addpayment(){
       try{
            const value=this.payment.value
            const method=this.payment.method
           const invoice_id=this.payment.invoice_id
            console.log(method,value);
             await this.axios.post(
              "http://localhost:8080/payments/add", {method,value,invoice_id}
            );
            console.log("addpayment ok");
            this.alertMessage("Created successfully ","success");
            this.payment={};
           }catch(e){
              this.alertMessage("please check your network connection ! ")
           }

     },
     async getinvoice(id_invoice){
         try {
       const {data}= await this.axios.get("http://localhost:8080/invoices/"+id_invoice)
       console.log(data);
       return data.id
     } catch (e) {
       this.alertMessage("invoice Id Not Found !!") ;
     }


     },
     create(){
       if(this.searchId){this.alertMessage("ID is generated by database automatically, remove it Please ! ") ;return;}
       if(!this.payment.method || !this.payment.value || ! this.payment.invoice_id){ this.alertMessage("Fill out the form  Please !!") ;return;}
      this.pInvoiceId= this.getinvoice(this.payment.invoice_id);
if(!this.pInvoiceId){this.alertMessage("invoice Id Not Found !!"); return -1;}

       console.log(this.pInvoiceId);
          this.addpayment()

     },

   },

}
</script>

<style lang="css" scoped>
.error{
  color: red;
}
.container{
  width: 80%;
 margin-top: 2%;
  display: flex;
  flex-direction: column;
  align-items: center;
}

input, select,button {
  width: 49%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
.inputDiv{
  width: 50%
}
.inputDiv input{ /* les trois derniers enfants */
  /* background-color: black; */
  display: inline-block;
  margin: auto 0.2rem;
  width:48%;
}

input[type=button]:hover {
  background-color: #4CAF50;
}



.notify{
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  position:absolute;
  top:10vh;
  width:100vw;
  height:0px;
  box-sizing:border-box;
  color:white;
  text-align:center;
  background:rgba(0,0,0,.6);
  box-sizing:border-box;
  z-index: 1;
   transition:height .5s;
}



.active{
  height:50px;
}
/* .success{
  background:#03a679;
  color:#f0f0f0;
} */

.failure{
  background:#ff3939;
  color:#f0f0f0;
}

</style>
